arb-dir: lib/src/l10n
output-dir: lib/src/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppRatingLocalizations
synthetic-package: false
format: true
nullable-getter: false
