name: leancode_app_rating
description: >
  Gather feedback with a 5-star rating or Yes/No survey. Includes device analytics and
  app store rating prompts for positive reviews.
repository: https://github.com/leancodepl/app-rating
homepage: https://github.com/leancodepl/app-rating/tree/main/mobile
version: 0.0.6

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  bloc_presentation: ^1.1.0
  cqrs: ^10.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  in_app_review: ^2.0.10
  intl: ^0.20.2
  leancode_contracts: ^0.8.0
  leancode_hooks: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  leancode_contracts_generator: ^0.14.0
  leancode_lint: ^17.0.0

flutter:
  assets:
    - assets/star-selected.png
    - assets/star-unselected.png
