name: leancode_app_rating test

on:
  push:
    branches: [main]
    tags-ignore: ['leancode_app_rating-v*']
    paths:
      - 'mobile/**'
  pull_request:
    branches: [main]
    paths:
      - 'mobile/**'

jobs:
  test:
    name: Flutter ${{ matrix.channel }}${{ matrix.version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.24.x

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true
          flutter-version: ${{ matrix.version }}

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run analyzer
        run: |
          flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Dry run pub publish
        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
        run: flutter pub publish --dry-run || true

      - uses: codecov/codecov-action@v1
        with:
          flags: leancode_app_rating
